function spm_TFCE
% TFCE Toolbox wrapper to call TFCE functions
%_______________________________________________________________________
% @(#)spm_TFCE.m Christian Gaser 2008/06/18

addpath(fileparts(which(mfilename)));

SPMid = spm('FnBanner',mfilename,'v1.02');
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','TFCE Toolbox');
spm_help('!ContextHelp',mfilename);
spm_help('!Disp','tfce.man','',Fgraph,'Threshold-Free Cluster Enhancement Toolbox');

fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
	'Label',	'TFCE',...
	'Separator',	'on',...
	'Tag',		'TFCE',...
	'HandleVisibility','on');
h1  = uimenu(h0,...
	'Label',	'Estimate',...
	'Separator',	'off',...
	'Tag',		'Estimate TFCE statistic',...
	'CallBack','cg_tfce_estimate;',...
	'HandleVisibility','on');
h2  = uimenu(h0,...
	'Label',	'Results',...
	'Separator',	'off',...
	'Tag',		'Non-parametric inference',...
	'CallBack','[hReg xSPM SPM] = cg_tfce_results(''Setup'');',...
	'HandleVisibility','on');
h3  = uimenu(h0,...
	'Label',	'Check for updates',...
	'Separator',	'off',...
	'Tag',		'Check for updates',...
	'CallBack','cg_tfce_update(1);',...
	'HandleVisibility','on');
