"""
Does the Python binding give what the MATLAB toolbox gives?

It must, and not approximately: both call the very same C. This is not a
reimplementation of TFCE in Python, it is the same max-tree with a different
caller, so anything other than bit-identical output means a binding bug -- a
transposed volume, a face list read 0-based, a float silently promoted.

The fixture is generated by ``make_fixture.py`` in this directory, which runs the
MATLAB mex-files over a set of inputs and stores what they returned. Regenerating
it needs MATLAB; running the test does not, which is the point -- CI can hold the
Python to the MATLAB's answer without MATLAB being anywhere near it.
"""

import pathlib

import numpy as np
import pytest

from tfce import adjacency_from_faces, tfce

FIXTURE = pathlib.Path(__file__).parent / "data" / "matlab_reference.npz"

pytestmark = pytest.mark.skipif(
    not FIXTURE.exists(),
    reason="MATLAB reference fixture not generated (see tests/make_fixture.py)",
)


@pytest.fixture(scope="module")
def ref():
    return np.load(FIXTURE)


def test_volume(ref):
    got = tfce(ref["vol"], E=float(ref["E_vol"]), H=float(ref["H_vol"]))
    assert np.array_equal(got, ref["ml_vol"])


def test_volume_batch(ref):
    got = tfce(
        ref["volB"], E=float(ref["E_vol"]), H=float(ref["H_vol"]), n_jobs=-1
    )
    assert np.array_equal(got, ref["ml_volB"])


def test_surface(ref):
    adj = adjacency_from_faces(ref["faces"], ref["surf"].shape[0])
    got = tfce(
        ref["surf"],
        adjacency=adj,
        E=float(ref["E_surf"]),
        H=float(ref["H_surf"]),
    )
    assert np.array_equal(got, ref["ml_surf"])


def test_surface_batch(ref):
    adj = adjacency_from_faces(ref["faces"], ref["surfB"].shape[0])
    got = tfce(
        ref["surfB"],
        adjacency=adj,
        E=float(ref["E_surf"]),
        H=float(ref["H_surf"]),
        n_jobs=-1,
    )
    assert np.array_equal(got, ref["ml_surfB"])
